-- AlterTable
ALTER TABLE "CatalogItem"
ADD COLUMN "barcode" TEXT,
ADD COLUMN "category" TEXT,
ADD COLUMN "unit" TEXT,
ADD COLUMN "manufacturerBrand" TEXT,
ADD COLUMN "location" TEXT,
ADD COLUMN "originalCode" TEXT,
ADD COLUMN "manufacturerCode" TEXT,
ADD COLUMN "sectorId" TEXT,
ADD COLUMN "expirationDate" TIMESTAMP(3),
ADD COLUMN "stockCurrent" DECIMAL(10,3),
ADD COLUMN "stockMinimum" DECIMAL(10,3),
ADD COLUMN "stockMaximum" DECIMAL(10,3),
ADD COLUMN "tablePrice" DECIMAL(10,2),
ADD COLUMN "supplierDiscountPercent" DECIMAL(5,2),
ADD COLUMN "purchasePrice" DECIMAL(10,2),
ADD COLUMN "profitPercent" DECIMAL(5,2),
ADD COLUMN "salePrice" DECIMAL(10,2),
ADD COLUMN "applicationDescription" TEXT,
ADD COLUMN "substituteCodes" JSONB,
ADD COLUMN "supplierQuotes" JSONB,
ADD COLUMN "taxCeanTrib" TEXT,
ADD COLUMN "taxNcm" TEXT,
ADD COLUMN "taxCest" TEXT,
ADD COLUMN "taxCfop" TEXT,
ADD COLUMN "taxCommercialUnit" TEXT,
ADD COLUMN "taxCommercialQuantity" DECIMAL(10,4),
ADD COLUMN "taxCommercialUnitValue" DECIMAL(10,2),
ADD COLUMN "taxTribUnit" TEXT,
ADD COLUMN "taxTribQuantity" DECIMAL(10,4),
ADD COLUMN "taxTribUnitValue" DECIMAL(10,2),
ADD COLUMN "taxInsuranceTotal" DECIMAL(10,2),
ADD COLUMN "taxDiscount" DECIMAL(10,2),
ADD COLUMN "taxFreightTotal" DECIMAL(10,2),
ADD COLUMN "taxOtherExpenses" DECIMAL(10,2),
ADD COLUMN "taxGrossTotal" DECIMAL(10,2),
ADD COLUMN "taxExTipi" TEXT,
ADD COLUMN "taxScaleIndicator" TEXT,
ADD COLUMN "taxManufacturerCnpj" TEXT,
ADD COLUMN "taxBenefitCode" TEXT,
ADD COLUMN "taxPurchaseOrder" TEXT,
ADD COLUMN "taxPurchaseOrderItem" TEXT,
ADD COLUMN "taxFciControlNumber" TEXT,
ADD COLUMN "taxFederalApproxPercent" DECIMAL(5,2),
ADD COLUMN "taxStateApproxPercent" DECIMAL(5,2),
ADD COLUMN "ipiTaxSituation" TEXT,
ADD COLUMN "ipiClass" TEXT,
ADD COLUMN "ipiLegalCode" TEXT,
ADD COLUMN "ipiProducerCnpj" TEXT,
ADD COLUMN "ipiSealCode" TEXT,
ADD COLUMN "ipiSealQuantity" DECIMAL(10,3),
ADD COLUMN "ipiCalculationType" TEXT,
ADD COLUMN "ipiBase" DECIMAL(10,2),
ADD COLUMN "ipiRate" DECIMAL(5,2),
ADD COLUMN "ipiUnitValue" DECIMAL(10,2),
ADD COLUMN "ipiValue" DECIMAL(10,2),
ADD COLUMN "icmsTaxSituation" TEXT,
ADD COLUMN "icmsCalculationType" TEXT,
ADD COLUMN "icmsBase" DECIMAL(10,2),
ADD COLUMN "icmsRate" DECIMAL(5,2),
ADD COLUMN "icmsValue" DECIMAL(10,2),
ADD COLUMN "icmsNotes" TEXT,
ADD COLUMN "pisTaxSituation" TEXT,
ADD COLUMN "pisCalculationType" TEXT,
ADD COLUMN "pisBase" DECIMAL(10,2),
ADD COLUMN "pisRate" DECIMAL(5,2),
ADD COLUMN "pisValue" DECIMAL(10,2),
ADD COLUMN "pisNotes" TEXT,
ADD COLUMN "cofinsTaxSituation" TEXT,
ADD COLUMN "cofinsCalculationType" TEXT,
ADD COLUMN "cofinsBase" DECIMAL(10,2),
ADD COLUMN "cofinsRate" DECIMAL(5,2),
ADD COLUMN "cofinsValue" DECIMAL(10,2),
ADD COLUMN "cofinsNotes" TEXT,
ADD COLUMN "importBase" DECIMAL(10,2),
ADD COLUMN "importExpenses" DECIMAL(10,2),
ADD COLUMN "importIof" DECIMAL(10,2),
ADD COLUMN "importValue" DECIMAL(10,2),
ADD COLUMN "importNotes" TEXT,
ADD COLUMN "fuelAnpCode" TEXT,
ADD COLUMN "fuelDescription" TEXT,
ADD COLUMN "fuelGlpPercent" DECIMAL(5,2),
ADD COLUMN "fuelNationalGasPercent" DECIMAL(5,2),
ADD COLUMN "fuelImportedGasPercent" DECIMAL(5,2),
ADD COLUMN "fuelCideBase" DECIMAL(10,2),
ADD COLUMN "fuelCideRate" DECIMAL(10,4),
ADD COLUMN "fuelCideValue" DECIMAL(10,2),
ADD COLUMN "fuelNotes" TEXT,
ADD COLUMN "ibsCbsCst" TEXT,
ADD COLUMN "ibsCbsClassification" TEXT,
ADD COLUMN "ibsUfRate" DECIMAL(5,2),
ADD COLUMN "ibsMunicipalRate" DECIMAL(5,2),
ADD COLUMN "cbsRate" DECIMAL(5,2),
ADD COLUMN "ibsValue" DECIMAL(10,2),
ADD COLUMN "cbsValue" DECIMAL(10,2),
ADD COLUMN "ibsCbsNotes" TEXT;

UPDATE "CatalogItem"
SET "salePrice" = "unitPrice"
WHERE "salePrice" IS NULL;

-- CreateIndex
CREATE INDEX "CatalogItem_barcode_idx" ON "CatalogItem"("barcode");

-- CreateIndex
CREATE INDEX "CatalogItem_category_idx" ON "CatalogItem"("category");

-- CreateIndex
CREATE INDEX "CatalogItem_sectorId_idx" ON "CatalogItem"("sectorId");

-- AddForeignKey
ALTER TABLE "CatalogItem" ADD CONSTRAINT "CatalogItem_sectorId_fkey" FOREIGN KEY ("sectorId") REFERENCES "Sector"("id") ON DELETE SET NULL ON UPDATE CASCADE;
