export type CompanySettings = {
  id: string;
  singletonKey: string;
  legalName: string;
  tradeName: string | null;
  document: string | null;
  stateRegistration: string | null;
  municipalRegistration: string | null;
  email: string | null;
  phone: string | null;
  whatsapp: string | null;
  website: string | null;
  cep: string | null;
  address: string | null;
  number: string | null;
  complement: string | null;
  neighborhood: string | null;
  city: string | null;
  state: string | null;
  ibgeCode: string | null;
  logoUrl: string | null;
  documentFooter: string | null;
  commercialNotes: string | null;
  createdAt: string;
  updatedAt: string;
};

export type CompanySettingsFormValues = {
  legalName: string;
  tradeName: string;
  document: string;
  stateRegistration: string;
  municipalRegistration: string;
  email: string;
  phone: string;
  whatsapp: string;
  website: string;
  cep: string;
  address: string;
  number: string;
  complement: string;
  neighborhood: string;
  city: string;
  state: string;
  ibgeCode: string;
  logoUrl: string;
  documentFooter: string;
  commercialNotes: string;
};
