-- AlterEnum
ALTER TYPE "ServiceOrderStatus" ADD VALUE IF NOT EXISTS 'AGUARDANDO_PECAS' AFTER 'EM_ANDAMENTO';
ALTER TYPE "ServiceOrderStatus" ADD VALUE IF NOT EXISTS 'IMPEDIDA' AFTER 'AGUARDANDO_PECAS';
