name: Deploy API

on:
  push:
    branches:
      - main
    paths:
      - "apps/api/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/oficina-api/car-workshop
            git fetch origin
            git reset --hard origin/main
            cd apps/api
            docker compose up -d --build --force-recreate
            docker image prune -f
